fpwm: functions.c FPGAtesting/Fpwm.c
	gcc FPGAtesting/Fpwm.c functions.c -lwiringPi -o ../Executables/fpwm
rotateTo: functions.c SystemsTesting/rotateTo.c
	gcc SystemsTesting/rotateTo.c functions.c -lwiringPi -o ../Executables/rotateTo
resetEnc: functions.c SystemsTesting/resetEnc.c
	gcc SystemsTesting/resetEnc.c functions.c -lwiringPi -o ../Executables/resetEnc
toggle: functions.c SystemsTesting/toggle.c
	gcc SystemsTesting/toggle.c functions.c -lwiringPi -o ../Executables/toggle
all_low: functions.c SystemsTesting/all_low.c
	gcc SystemsTesting/all_low.c functions.c -lwiringPi -o ../Executables/all_low
colorRead: functions.c SystemsTesting/colorRead.c
	gcc SystemsTesting/colorRead.c functions.c -lwiringPi -o ../Executables/colorRead
rotateCBy90: functions.c SystemsTesting/Centrifuge/rotateCBy90.c
	gcc SystemsTesting/Centrifuge/rotateCBy90.c functions.c -lwiringPi -o ../Executables/rotateCBy90
rotateCByTeeth: functions.c SystemsTesting/Centrifuge/rotateCByTeeth.c
	gcc SystemsTesting/Centrifuge/rotateCByTeeth.c functions.c -lwiringPi -o ../Executables/rotateCByTeeth
