fpwm: functions.c FPGAtesting/Fpwm.c
	gcc FPGAtesting/Fpwm.c functions.c -lwiringPi -o ../Executables/fpwm
rotateTo: functions.c SystemsTesting/rotateTo.c
	gcc SystemsTesting/rotateTo.c functions.c -lwiringPi -o ../Executables/rotateTo
resetEnc: functions.c SystemsTesting/resetEnc.c
	gcc SystemsTesting/resetEnc.c functions.c -lwiringPi -o ../Executables/resetEnc
toggle: functions.c SystemsTesting/toggle.c
	gcc SystemsTesting/toggle.c functions.c -lwiringPi -o ../Executables/toggle
all_low: functions.c SystemsTesting/all_low.c
	gcc SystemsTesting/all_low.c functions.c -lwiringPi -o ../Executables/all_low

